export { default as Button } from './ui/Button'
export { default as Input } from './ui/Input'
export { Textarea } from './ui/Input'
export { default as Modal } from './ui/Modal'
export { ConfirmModal } from './ui/Modal'
export { default as Badge } from './ui/Badge'
export { VisitStatusBadge, LanguageBadge } from './ui/Badge'
export { default as Spinner } from './ui/Spinner'
export { PageLoader, SkeletonCard, DotPulse } from './ui/Spinner'
export { default as Avatar } from './ui/Avatar'
export { default as Card } from './ui/Card'
export { default as EmptyState } from './ui/EmptyState'
export { default as Tabs } from './ui/Tabs'
export { default as LanguageSwitcher } from './ui/LanguageSwitcher'
export { LANGUAGES } from './ui/LanguageSwitcher'

export { default as StatsGrid } from './doctor/StatsGrid'
export { default as PatientCard } from './doctor/PatientCard'
export { default as VisitRow } from './doctor/VisitRow'
export { default as AIStatusBadge } from './doctor/AIStatusBadge'
export { default as WhatsAppStatusBadge } from './doctor/WhatsAppStatusBadge'
export { default as VoiceInput } from './doctor/VoiceInput'
export { default as AISummaryReview } from './doctor/AISummaryReview'
export { default as PatientSearch } from './doctor/PatientSearch'
export { default as NotificationBell } from './doctor/NotificationBell'

export { default as VisitHeader } from './patient/VisitHeader'
export { default as DiagnosisCard } from './patient/DiagnosisCard'
export { default as MedicineSchedule } from './patient/MedicineSchedule'
export { default as VitalCard } from './patient/VitalCard'
export { default as VitalsGrid } from './patient/VitalsGrid'
export { default as RedFlagAlerts } from './patient/RedFlagAlerts'
export { default as DietAdvice } from './patient/DietAdvice'
export { default as FollowUpReminder } from './patient/FollowUpReminder'

export { default as SOAPSection } from './visit/SOAPSection'
export { default as QuickSummary } from './visit/QuickSummary'
export { default as MedicalTermHighlight } from './visit/MedicalTermHighlight'
export { default as NextActionsChecklist } from './visit/NextActionsChecklist'
export { default as ChatPanel } from './visit/ChatPanel'
export { default as AttachmentCard } from './visit/AttachmentCard'
export { default as ScribeRecorder } from './visit/ScribeRecorder'
export { default as AIProcessingStatus } from './visit/AIProcessingStatus'
export { default as LanguageBanner } from './visit/LanguageBanner'

export { default as HeartRateChart } from './charts/HeartRateChart'
export { default as WeightChart } from './charts/WeightChart'
export { default as BloodPressureChart } from './charts/BloodPressureChart'
export { default as BloodSugarChart } from './charts/BloodSugarChart'
export { default as VitalsTrendMini } from './charts/VitalsTrendMini'

export { default as LoginForm } from './forms/LoginForm'
export { default as DoctorRegisterForm } from './forms/DoctorRegisterForm'
export { default as OTPVerifyForm } from './forms/OTPVerifyForm'
export { default as NewVisitForm } from './forms/NewVisitForm'
export { default as PatientQuickAddForm } from './forms/PatientQuickAddForm'
export { default as SendToPatientForm } from './forms/SendToPatientForm'

export { default as DoctorLayout } from './layout/DoctorLayout'
export { default as PatientLayout } from './layout/PatientLayout'

export { default as ProtectedRoute } from './common/ProtectedRoute'
export { default as Navbar } from './common/Navbar'
export { default as PageHeader } from './common/PageHeader'
export { default as ErrorBoundary } from './common/ErrorBoundary'
