apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shifa-ingress
spec:
  rules:
    - host: shifa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shifa-backend
                port:
                  number: 80
