services:
  postgres:
    image: postgres:15
    container_name: shifa-postgres
    environment:
      POSTGRES_DB: shifadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: shifa-redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: shifa-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data: