ALTER TABLE visits ADD COLUMN IF NOT EXISTS follow_up_date DATE;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'COMPLETED';
ALTER TABLE visits ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE patients ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(255);
