CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

CREATE TYPE user_role AS ENUM (
  'DOCTOR', 'PATIENT', 'ADMIN', 'RECEPTIONIST'
);

CREATE TYPE language_code AS ENUM (
  'EN', 'HI', 'TA', 'TE', 'BN', 'MR', 'GU', 'KN', 'ML', 'PA'
);

CREATE TYPE gender_type AS ENUM (
  'MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'
);

CREATE TYPE visit_status AS ENUM (
  'DRAFT',
  'NOTES_TAKEN',
  'AI_PROCESSING',
  'REVIEWED',
  'SENT_TO_PATIENT',
  'COMPLETED'
);

CREATE TYPE whatsapp_delivery_status AS ENUM (
  'NOT_SENT', 'QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED'
);
