ALTER TABLE visits
    ADD COLUMN IF NOT EXISTS visit_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'DOCTOR',
    ADD COLUMN IF NOT EXISTS audio_filename VARCHAR(255),
    ADD COLUMN IF NOT EXISTS audio_content_type VARCHAR(100);
