ALTER TABLE visits ADD COLUMN follow_up_date DATE;
ALTER TABLE visits ADD COLUMN status VARCHAR(50) DEFAULT 'COMPLETED';
ALTER TABLE visits ADD COLUMN deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE patients ADD COLUMN deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE patients ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE patients ADD COLUMN delete_reason VARCHAR(255);
